# Generated by Django 5.0.4 on 2024-04-19 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_photo', models.FileField(upload_to='exam-photos')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='abiturient.department')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255, verbose_name='фамилия абитуриента')),
                ('patronymic', models.CharField(max_length=255, verbose_name='отчество абитуриента')),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('degree', models.CharField(choices=[('магистратура', 'магистратура'), ('докторантура', 'докторантура')], max_length=255, verbose_name='степень')),
                ('diploma', models.FileField(upload_to='diplomas/')),
                ('diploma_equivalency', models.FileField(upload_to='diplomas-equivalency')),
                ('diploma_supplement', models.FileField(upload_to='diploma-supplement')),
                ('passport_front', models.FileField(upload_to='passport-front')),
                ('passport_back', models.FileField(upload_to='passport-back')),
                ('photo', models.FileField(upload_to='abiturient-photos')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates')),
                ('lang_certificate', models.FileField(blank=True, null=True, upload_to='language-certificates')),
                ('confirmed', models.BooleanField(default=False)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='abiturient.department')),
            ],
        ),
    ]
