# Generated by Django 5.0.4 on 2024-04-20 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='request',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='request',
            name='diploma_equivalency',
        ),
        migrations.RemoveField(
            model_name='request',
            name='diploma_supplement',
        ),
        migrations.RemoveField(
            model_name='request',
            name='email',
        ),
        migrations.RemoveField(
            model_name='request',
            name='lang_certificate',
        ),
        migrations.RemoveField(
            model_name='request',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='request',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='request',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('магистратура', 'магистратура'), ('докторантура', 'докторантура')], default='магистратура', max_length=255),
        ),
        migrations.AlterField(
            model_name='request',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='passport_back',
            field=models.FileField(blank=True, null=True, upload_to='passport-back'),
        ),
        migrations.AlterField(
            model_name='request',
            name='passport_front',
            field=models.FileField(blank=True, null=True, upload_to='passport-front'),
        ),
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='abiturient-photos'),
        ),
        migrations.CreateModel(
            name='CertificateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='certificate-images')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='abiturient.request')),
            ],
        ),
    ]
