# Generated by Django 5.0.4 on 2024-04-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0003_remove_request_certificate_remove_request_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='is_foreigner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='passport_back',
            field=models.FileField(blank=True, null=True, upload_to='passport-back/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='passport_front',
            field=models.FileField(blank=True, null=True, upload_to='passport-front/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='abiturient-photos/'),
        ),
    ]
