# Generated by Django 5.0.4 on 2024-04-20 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0004_request_email_request_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='image',
            field=models.ImageField(upload_to='certificate-images/'),
        ),
    ]
