# Generated by Django 5.0.4 on 2024-04-20 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0005_alter_certificateimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='diploma',
        ),
        migrations.RemoveField(
            model_name='request',
            name='passport_back',
        ),
        migrations.RemoveField(
            model_name='request',
            name='passport_front',
        ),
        migrations.RemoveField(
            model_name='request',
            name='photo',
        ),
    ]
