# Generated by Django 5.0.4 on 2024-04-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0006_remove_request_diploma_remove_request_passport_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='diplomas/'),
        ),
        migrations.AddField(
            model_name='request',
            name='passport_back',
            field=models.FileField(blank=True, null=True, upload_to='passport-back/'),
        ),
        migrations.AddField(
            model_name='request',
            name='passport_front',
            field=models.FileField(blank=True, null=True, upload_to='passport-front/'),
        ),
        migrations.AddField(
            model_name='request',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='abiturient-photos/'),
        ),
    ]
