# Generated by Django 5.0.4 on 2024-04-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0007_request_diploma_request_passport_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('magistrate', 'magistrate'), ('doctorate', 'doctorate')], default='magistrate', max_length=255),
        ),
    ]
