# Generated by Django 5.0.4 on 2024-04-20 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0008_alter_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateimage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to='abiturient.request'),
        ),
    ]
