# Generated by Django 5.0.4 on 2024-04-20 07:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0009_alter_certificateimage_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('exam', models.ManyToManyField(to='abiturient.exam', verbose_name='exam_grade')),
            ],
        ),
    ]
