# Generated by Django 5.0.4 on 2024-04-20 07:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0010_examgrade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examgrade',
            name='grader',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='exam_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examgrade',
            name='grade',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
