# Generated by Django 5.0.4 on 2024-04-20 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0011_examgrade_grader_alter_examgrade_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='examgrade',
            name='grader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_grades', to=settings.AUTH_USER_MODEL),
        ),
    ]
