# Generated by Django 5.0.4 on 2024-04-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ABITURIENT', 'ABITURIENT'), ('DEAN', 'Dean'), ('COMMISSIONER', 'Commissioner'), ('ASSISTANT', 'Assistant')], default='DEAN', max_length=20),
        ),
    ]
